# Generated by Django 4.0.3 on 2022-03-23 04:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='all_subjects',
            fields=[
                ('sub_code', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('sub_name', models.CharField(max_length=100)),
                ('year', models.PositiveIntegerField()),
                ('semester', models.PositiveIntegerField()),
                ('offer_stats', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='head_access',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email1', models.EmailField(max_length=100)),
                ('passw1', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='student_accounts',
            fields=[
                ('stud_id', models.CharField(editable=False, max_length=100, primary_key=True, serialize=False)),
                ('fn', models.CharField(max_length=100)),
                ('ln', models.CharField(max_length=100)),
                ('section', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('passw', models.CharField(max_length=100)),
                ('stud_stats', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='student_request',
            fields=[
                ('trans_id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('remarks', models.CharField(max_length=100)),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='Adding_App.all_subjects')),
                ('stud_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='Adding_App.student_accounts')),
                ('sub_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='Adding_App.all_subjects')),
                ('sub_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='Adding_App.all_subjects')),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='Adding_App.all_subjects')),
            ],
        ),
    ]
