# Generated by Django 4.0.3 on 2022-04-29 02:54

import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='all_subjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_code', models.CharField(max_length=100, unique=True)),
                ('sub_name', models.CharField(max_length=100)),
                ('year', models.PositiveIntegerField()),
                ('semester', models.PositiveIntegerField()),
                ('offer_stats', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('section', models.CharField(choices=[('1A', 'BET-COET-S-1A'), ('1B', 'BET-COET-NS-1B'), ('2A', 'BET-COET-S-2A'), ('2B', 'BET-COET-NS-2B'), ('3A', 'BET-COET-S-3A'), ('3B', 'BET-COET-NS-3B'), ('4A', 'BET-COET-S-4A'), ('4B', 'BET-COET-NS-4B')], max_length=30, verbose_name='section')),
                ('stud_id', models.IntegerField(unique=True, verbose_name='stud_id')),
                ('stud_stats', models.CharField(default='Processing', max_length=30)),
                ('image', models.ImageField(default='', upload_to='images')),
                ('userType', models.CharField(choices=[('STDNT', 'Student'), ('DH', 'Department Head'), ('PIC', 'Person-in-charge')], default='STDNT', max_length=30, verbose_name='userType')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='student_request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('grades', models.PositiveIntegerField()),
                ('remarks', models.CharField(max_length=100)),
                ('stud_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stud_id', to='Adding_App.all_subjects', verbose_name='stud_id')),
                ('sub_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject', to='Adding_App.all_subjects', verbose_name='sub_code')),
            ],
        ),
    ]
